print ("Esta es la practica en equipo de:")
print ("Xadanny Guadalupe Pérez Castillo")
print ("Atlzin Nichdali Escalante Urdanivia")
print ("Brian Iván Jimenez Ricardo")
print ("Ariam Melanie Muñoz Rodriguez")